name: Jet Stream Bot

on:
  #push
  schedule:
    - cron: '50 3,9,15,21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout allows us to use the files in this repository.
    - uses: actions/checkout@v4
    - name: Setup Miniconda
      # This sets up conda... 
      # ...auto-creates a test environment (super annoying)...
      # ... and installs the python version and dependencies there.
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        miniconda-version: latest
        python-version: 3.7

    - name: Install apt-get dependencies
      shell: bash -el {0}
      run: |
        # This needs to be installed via apt-get...
        sudo apt-get install proj-bin  libproj-dev

    - name: Install conda dependencies
      shell: bash -el {0}
      run: |
        # ... but most everything else can come via conda-forge.
        conda install -c conda-forge wheel==0.37.0 numpy==1.21.1 xarray==0.20.1 netcdf4==1.5.7 matplotlib=3.4 cartopy=0.17 metpy=1.1
    
    - name: Run code
      shell: bash -el {0}
      run: |
        # Run the code!
        python jet_stream_bot.py
        
    # We created some files. But we need to commit them to the repository.
    - name: Commit files
      shell: bash -el {0}
      run: |
          git config --local user.email ${{ secrets.SECRET_MAIL_FROM }}
          git config --local user.name ${{ secrets.SECRET_GITHUB_USERNAME }}
          git add .        # Adds file to commit
          git add --all    # Adds only the file, not the folder where Python & conda was set up.
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add changes'
          
    # Now push committed changes to the repo.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
