name: when_model_updates

on: [push]

#on:
#  schedule:
#    - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install csv datetime

    - name: Run code
      run: python when_model_updates.py
