name: when_model_updates

on: [push]

#on:
#  schedule:
#    - cron: '15 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7

    - name: Import dependencies
      run: pip install xarray pydap netCDF4

    - name: chmod
      run: chmod 666 ./model_available.csv

    - name: Run code
      run: python when_model_updates.py

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
