name: when_model_updates

on: [push]

#on:
#  schedule:
#    - cron: '15 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7

    - name: Import dependency
      run: pip install xarray pydap netCDF4

    - name: Run code
      run: python when_model_updates.py
