name: when_model_updates

on:
  push
  #schedule:
  #  - cron: '*/5 3,9,15,21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3

    - name: Import dependencies
      shell: bash -el {0}
      run: conda install conda-forge::xarray netcdf4 hdf5

    - name: Run code
      shell: bash -el {0}
      run: |
        echo "--> conda info"
        conda info
        echo "--> pwd"
        pwd
        echo "--> ls *.py"
        ls *.py
        echo "--> conda list xarray"
        conda list xarray
        echo "--> conda env list"
        conda env list
        echo "--> conda activate base"
        conda activate base
        echo "--> python -c"
        python -c "import xarray"
        echo "--> run code"
        python when_model_updates.py

    - name: Commit files
      shell: bash -el {0}
      run: |
          git config --local user.email ${{ secrets.SECRET_MAIL_FROM }}
          git config --local user.name ${{ secrets.SECRET_GITHUB_USERNAME }}
          git add .        # Adds file to commit
          git add --all    # Adds only the file, not the Python setup folder.
          # git commit -m "Add changes"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add changes'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
